### ISSUE TITLE
Link to cheatsheet does not work

### ISSUE THREAD

**Issue by soukhova** [paezha/spatial-analysis-r#3]
update link on line 348, link no longer works.
"Check the `ggplot2` [Cheat Sheet](https://www.rstudio.com/wp-content/uploads/2015/03/ggplot2-cheatsheet.pdf) "

Cheatsheets are available here: https://www.rstudio.com/resources/cheatsheets/

**Comment by paezha** [comment]
Fixed for the 2024 edition!
