### ISSUE TITLE
Cannot export the book to PDF nor EPUB

### ISSUE THREAD

**Issue by umbe1987** [paezha/spatial-analysis-r#6]
First of all, thank you for making this beautiful resource public!

Just reporting that at the moment the button to download to PDF or EPUB are not working (they both point to a non existing page).

PDF: https://paezha.github.io/spatial-analysis-r/spatial-analysis-R.pdf
EPUB: https://paezha.github.io/spatial-analysis-r/spatial-analysis-R.epub

![image](https://user-images.githubusercontent.com/15016826/213481997-5c11118d-d3d9-414d-913b-b4b2a6974c5b.png)

**Comment by paezha** [comment]
Since the pdf version can be recreated using package [{isdas}](https://paezha.github.io/isdas/) I removed the export button.
