### ISSUE TITLE
`rm(list = ls())` is not as good practice as it seems

### ISSUE THREAD

**Issue by jospueyo** [paezha/spatial-analysis-r#8]
I'm enjoying your book, thanks for it! However, everytime I read that you recommend doing `rm(list = ls())`, this comes to my mind: https://rstats.wtf/source-and-blank-slates#rm-list-ls

**Comment by paezha** [comment]
This is a valid point. However, the alternatives are overly complicated for the students that are the main audience of the book. I am keeping this, but with a comment about restarting the session along the following lines:

As usual, it is good practice to begin with a clean session to make sure that you do not have extraneous items there when you begin your work. The best practice is to restart the `R` session, which can be accomplished for example with `command/ctrl + shift + F10`. An alternative to _only_ purge user-created objects from memory is to use the `R` command `rm` (for "remove"), followed by a list of items to be removed. To clear the workspace from _all_ objects, do the following:

```{r ch07-clear-workspace}
rm(list = ls())
```
Note that `ls()` lists all objects currently on the workspace.
