### ISSUE TITLE
`spdep` works with `sf` objects

### ISSUE THREAD

**Issue by jospueyo** [paezha/spatial-analysis-r#9]
In chapter 21, you explain that an `sf` object must be converted to `sp` before calculating `poly2nb()`. Since last versions (I don't know exactly which) it is not longer necessary. Indeed, `sf` objects are the recommended way to interact with the `spdep` package. 

https://r-spatial.github.io/spdep/news/index.html#version-12-7-2022-10-01

**Comment by paezha** [comment]
Revised to use only `sf`.
